### PR TITLE
Bugfix/ZCS-3940 Configure STAF on mysql node

### PR DESCRIPTION
**Pull request by RohitVyawahare**
Configure STAF on mysql node and add packages on base for Genesis execution.

### CODE REVIEW

**Comment by Prashantsurana** [comment]
Why do we need STAF on mysql? 
Is it just for checking the maria db version?

**Comment by RohitVyawahare** [comment]
@Prashantsurana There are certain Genesis tests that validates the output of mysql queries.

**Comment by RohitVyawahare** [comment]
Based on the discussion with @Prashantsurana , removed the STAF dependency on mysql node. Made necessary chances in Genesis to do that. Here is the PR https://github.com/Zimbra/zm-genesis/pull/28

**Comment by gordyt** [comment]
@RohitVyawahare Is this pull request still needed? If so, should rebase out the last two commits completely and update this pull request branch.  The third commit just reverses the second commit and there is no need to merge that.

**Pull request closed without merging**
